In [1]:
import numpy as np

In [6]:
a = np.array([[4, 1, 2, -1],
              [3, 6, -1, 2],
              [2, -1, 5, -3],
              [4, 1, -3, -8]],float)

a

array([[ 4.,  1.,  2., -1.],
       [ 3.,  6., -1.,  2.],
       [ 2., -1.,  5., -3.],
       [ 4.,  1., -3., -8.]])

In [7]:
b = np.array([2, -1, 3, 2], float)
b

array([ 2., -1.,  3.,  2.])

In [8]:
(n,) = np.shape(b)  # numpy array size function
n

4

In [20]:
x = np.full(n, 1, float)  # initial guess = 1.0
x

array([1., 1., 1., 1.])

In [21]:
xnew = np.empty(n,float)  # construct xnew array
xnew

array([1., 1., 1., 1.])

In [22]:
iterlimit = 100  # max number of iterations
tolerance = 1.0e-6  # degree of accuracy

In [23]:
# Iterations
for iteration in range(iterlimit):
    print(f"\niteration={iteration}")
    print(x)
    for i in range(n):
        s = 0
        for j in range(n):
            if j != i:
                s += a[i,j]*x[j]
        xnew[i] = -1/a[i,i] * (s - b[i])

    # convergence condition
    if (abs(xnew - x) < tolerance).all():
        break  # exit the loop
    else:
        x = np.copy(xnew)  # assign a copy of all xnew elements to x

print('Number of iterations: %d' % (iteration+1))
print('The solution of the system:')
print(x)


iteration=0
[1. 1. 1. 1.]

iteration=1
[-0.         -0.83333333  1.          0.        ]

iteration=2
[ 0.20833333 -0.          0.43333333 -0.72916667]

iteration=3
[ 0.10104167  0.04444444  0.07916667 -0.30833333]

iteration=4
[ 0.37222222 -0.10121528  0.38347222 -0.22361111]

iteration=5
[ 0.27766493 -0.2143287   0.29670139 -0.22034288]

iteration=6
[ 0.35014576 -0.18260127  0.31386256 -0.24922164]

iteration=7
[ 0.32641363 -0.20635524  0.27388845 -0.21545074]

iteration=8
[ 0.3607819  -0.21240849  0.29889306 -0.21529576]

iteration=9
[ 0.34983165 -0.22547685  0.28402809 -0.20824501]

iteration=10
[ 0.36229392 -0.22482948  0.29002496 -0.20977931]

iteration=11
[ 0.35875006 -0.22954969  0.28424895 -0.20571609]

iteration=12
[ 0.36383393 -0.23009484  0.28716039 -0.20591204]

iteration=13
[ 0.36246551 -0.23208622  0.28490024 -0.20453004]

iteration=14
[ 0.36443893 -0.23223937  0.28587853 -0.20461561]

iteration=15
[ 0.36396667 -0.2330345   0.28500719 -0.20401491]

iteration=16
[ 0.3647