In [41]:
import numpy as np

In [42]:
a = np.array([[7, 1, 1],
              [-3, 7, -1],
              [-2, 5, 9]],float)

a

array([[ 7.,  1.,  1.],
       [-3.,  7., -1.],
       [-2.,  5.,  9.]])

In [43]:
b = np.array([6, -26, 1], float)
b

array([  6., -26.,   1.])

In [44]:
(n,) = np.shape(b)  # numpy array size function
n

3

In [45]:
x = np.full(n, 1, float)  # initial guess = 1.0
x

array([1., 1., 1.])

In [46]:
xnew = np.empty(n,float)  # construct xnew array
xnew

array([1., 1., 1.])

In [47]:
iterlimit = 100  # max number of iterations
tolerance = 1.0e-9  # degree of accuracy

In [48]:
# Iterations
for iteration in range(iterlimit):
    print(f"\niteration={iteration}")
    print(x)
    for i in range(n):
        s = 0
        for j in range(n):
            if j != i:
                s += a[i,j]*x[j]
        xnew[i] = -1/a[i,i] * (s - b[i])

    # convergence condition
    if (abs(xnew - x) < tolerance).all():
        break  # exit the loop
    else:
        x = np.copy(xnew)  # assign a copy of all xnew elements to x

print('Number of iterations: %d' % (iteration+1))
print('The solution of the system:')
print(x)


iteration=0
[1. 1. 1.]

iteration=1
[ 0.57142857 -3.14285714 -0.22222222]

iteration=2
[ 1.33786848 -3.50113379  1.98412698]

iteration=3
[ 1.07385811 -2.8574668   2.35348954]

iteration=4
[ 0.92913961 -2.91784802  1.9372278 ]

iteration=5
[ 0.99723146 -3.0393362   1.93861325]

iteration=6
[ 1.01438899 -3.00995605  2.02123821]

iteration=7
[ 0.99838826 -2.99079926  2.00872869]

iteration=8
[ 0.99743865 -2.99944379  1.99453031]

iteration=9
[ 1.00070192 -3.0018791   1.99912181]

iteration=10
[ 1.0003939  -2.99982463  2.00119993]

iteration=11
[ 0.99980353 -2.99965977  1.99999011]

iteration=12
[ 0.99995281 -3.00008562  1.99976732]

iteration=13
[ 1.00004547 -3.00005346  2.00003708]

iteration=14
[ 1.00000234 -2.99997522  2.00003981]

iteration=15
[ 0.99999077 -2.99999331  1.99998675]

iteration=16
[ 1.00000094 -3.00000585  1.99999423]

iteration=17
[ 1.00000166 -3.00000042  2.00000346]

iteration=18
[ 0.99999957 -2.9999988   2.0000006 ]

iteration=19
[ 0.99999974 -3.0000001   1.9999992