In [16]:
import numpy as np

In [31]:
a = np.array([[4, 1, 2, -1],
              [3, 6, -1, 2],
              [2, -1, 5, -3],
              [4, 1, -3, -8]],float)

a

array([[ 4.,  1.,  2., -1.],
       [ 3.,  6., -1.,  2.],
       [ 2., -1.,  5., -3.],
       [ 4.,  1., -3., -8.]])

In [25]:
b = np.array([2, -1, 3, 2], float)
b

array([ 2., -1.,  3.,  2.])

In [26]:
(n,) = np.shape(b)  # numpy array size function
n

4

In [27]:
x = np.full(n, 1, float)  # initial guess = 1.0
x

array([1., 1., 1., 1.])

In [28]:
xdiff = np.empty(n, float)
xdiff

array([1., 1., 1., 1.])

In [29]:
iterlimit = 100  # max number of iterations
tolerance = 1.0e-6  # degree of accuracy

In [30]:
# Iterations
for iteration in range(iterlimit):
    print(f"\niteration={iteration}")
    print(x)
    for i in range(n):
        s = 0
        for j in range(n):
            if j != i:
                s += a[i,j]*x[j]
        xnew = -1/a[i,i] * (s - b[i])  # xnew is scalar
        xdiff[i] = abs(xnew - x[i])  # compute the absolute difference
        x[i] = xnew  # assign the new value to x[i]
    if (xdiff < tolerance).all(): # check convergence of all equations
        break

print('Number of iterations: %d' % (iteration+1))
print('The solution of the system:')
print(x)


iteration=0
[1. 1. 1. 1.]

iteration=1
[ 0.5        -4.         -4.33333333 10.08333333]

iteration=2
[ 24.95833333 -82.08333333 -21.97222222 198.82638889]

iteration=3
[  313.12847222 -1010.74305556  -450.61342593  2338.22974537]

iteration=4
[  4129.50665509 -13279.57002315  -5156.79378858  31067.05319252]

iteration=5
[  52853.77924865 -170035.47622492  -69053.26159015  396300.12900672]

iteration=6
[  682066.60937299 -2193860.78530494  -878666.12662225  5119150.37854423]

iteration=7
[  8778461.49171948 -28237364.3350892  -11358908.13218836
  65864947.7015942 ]

iteration=8
[ 1.13076011e+08 -3.63721280e+08 -1.46112274e+08  8.48493688e+08]

iteration=9
[ 1.45616058e+09 -4.68392407e+09 -1.88241042e+09  1.09263261e+10]

iteration=10
[ 1.87535532e+10 -6.03230660e+10 -2.42398207e+10  1.40718958e+11]

iteration=11
[ 2.41516455e+11 -7.76867222e+11 -3.12184354e+11  1.81223481e+12]

iteration=12
[ 3.11037948e+12 -1.00049144e+13 -4.02042498e+12  2.33389616e+13]

iteration=13
[ 4.00570476e+1